create table choices (
    id int4 generated by default as identity, 
    name varchar(50) not null, 
    question_id int4, 
    constraint pk_choices primary key (id)
);

create table questions (
    id int4 generated by default as identity, 
    question_type varchar(13) not null, 
    title varchar(50) not null, 
    constraint pk_questions primary key (id)
);

create table survey_contains_question (
    survey_id int4 not null, 
    question_id int4 not null, 
    constraint pk_survey_contains_question primary key (survey_id, question_id)
);

create table surveys (
    id int4 generated by default as identity, 
    title varchar(30) not null, 
    constraint pk_surveys primary key (id)
);

alter table choices 
    add constraint FK_choices_qid
    foreign key (question_id) references questions;

alter table survey_contains_question 
    add constraint FK_survey_contains_question_sid 
    foreign key (question_id) 
    references questions;

alter table survey_contains_question 
    add constraint FK_survey_contains_question_qid 
    foreign key (survey_id) 
    references surveys;
